Support endless shell pipe streams
beatlabs/proton pull request #2
Opened 2022-02-02 11:05 UTC by peterklijn

Proton did not work with streams of multiple messages, this PR changes the behaviour of reading from unix pipes.

Because Protobuf messages can (and often do) contain newline characters, we can't rely on `\n` for knowing if a message is over. Instead we need a different line separator. With this change, Proton uses `--END--` on a new line as a separator, and will print successful parses to STDOUT, and unsuccessful parses to STDERR.

The line separator must be on a separate line, but the value can be overwritten with `--line-separator` (or `-l`).

The Readme contains a couple of examples on how to use this with a fake producer, as well as example code for using Kafkacat.

2022-02-02 11:12 UTC, gmaz42 commented on cmd/json.go
> +				case e, ok := <-errorCh:
Since both channels are closed (`resultCh` and `errorCh`) I think the errors channel should be spooled first, so that no error is ever ignored.

2022-02-02 11:13 UTC, gmaz42 commented on cmd/json.go
> +				case e, ok := <-errorCh:
```go
for err := range errorCh {
      // handle error
}

2022-02-02 11:14 UTC, gmaz42 commented on internal/json/json.go
> +// next begins, so instead it looks for a line containing only a specified LineSeparator (defaults to DefaultLineSeparator).
I think we should disclose here that the `LineSeparator` may as well be in the proto bytes and in such cases the messasge parsing would fail.

2022-02-02 11:15 UTC, gmaz42 commented on README.md
> +stdbuf -o0 kcat -b my-broker:9092 -t my-topic -f '%s\n--END--\n' -o beginning | proton json -f ./my-schema.proto
:+1: excellent docs/examples

2022-02-02 11:40 UTC, peterklijn commented on internal/json/json.go
> +// next begins, so instead it looks for a line containing only a specified LineSeparator (defaults to DefaultLineSeparator).
I would classify that as "extremely unlikely", close to impossible, as this separator should be the only thing on the entire line.
Anyway, I've added a warning of sorts to the message :)

2022-02-02 12:43 UTC, gmaz42 commented on cmd/json.go
> +				case e, ok := <-errorCh:
Example: https://go.dev/play/p/2Sa5iQ7Wg6g

2022-02-02 13:13 UTC, rbroggi requested changes

2022-02-02 13:13 UTC, rbroggi commented on README.md
> +  -l, --line-separator string   Line separator string in case of piping data
I don't think it's a good idea to call it `line-separator` - it's rather a byte-stream split marker. Line-separator is something that does not make sense in bynary-format

2022-02-02 13:13 UTC, rbroggi commented on README.md
> +  -l, --line-separator string   Line separator string in case of piping data
other suggestions:

* --message-separator-marker
* --binary-stream-split

2022-02-02 13:13 UTC, rbroggi commented on README.md
> +Because Proto bytes can contain newlines (`\n`) and often do, we need to use a different line separator when consuming.
```suggestion
Because Proto bytes can contain newlines (`\n`) and often do, we need to use a different marker to delimit the end of a message byte-stream and the beginning of the next.
```

2022-02-02 13:13 UTC, rbroggi commented on README.md
> +Proton expects this separator to be on a new line, and expects `--END--` by default.
I'm not sure what you mean here by `new line`

2022-02-02 17:53 UTC, rbroggi requested changes

2022-02-02 17:53 UTC, rbroggi commented on internal/json/json.go
> +func (c Converter) ConvertStream(r io.Reader) (resultCh chan []byte, errorCh chan error) {
as discussed offline in a call we might want to change approach and simply split our input buffer **on the marker**. 

For that I have created an example (with unit-tests) on how to do that: https://go.dev/play/p/C_VSITREy-g

2022-02-02 17:59 UTC, rbroggi commented on internal/json/json.go
> +func (c Converter) ConvertStream(r io.Reader) (resultCh chan []byte, errorCh chan error) {
this will also simplify a bit the code IMO:

```go
reader := bufio.NewReader(r)
s := bufio.NewScanner(r)
s.Split(SplitMessagesOnMarker(tt.marker))
for s.Scan() {
    resultCh <- s.Bytes()
}
if err := s.Err(); err != nil {
    errorCh <- err
}
```

2022-02-02 18:01 UTC, rbroggi requested changes

2022-02-02 18:01 UTC, rbroggi commented on internal/json/json.go
> +func (c Converter) ConvertStream(r io.Reader) (resultCh chan []byte, errorCh chan error) {
I also suggest to return `receiver channels`:
```suggestion
func (c Converter) ConvertStream(r io.Reader) (resultCh <-chan []byte, errorCh <-chan error) {
```

2022-02-02 18:10 UTC, rbroggi commented on cmd/json.go
> +			resultCh, errorCh := c.ConvertStream(r)
With the new solution suggested, I think the channels are an overkill. Why not simply:

```go
reader := bufio.NewReader(r) 
s := bufio.NewScanner(r) 
s.Split(SplitMessagesOnMarker(tt.marker)) 
for s.Scan() { 
   jsonMsg, err := convertToJson(s.Bytes())
} 
if err := s.Err(); err != nil { 
    errorCh <- err
}

```

2022-02-02 19:30 UTC, rbroggi commented
I have a suggestion for the overall algorithm:

if you have a look at [this implementation](https://go.dev/play/p/x1xahorHuOB) of the byte-stream splitting, I think it would make sense to:

1. Use the same method (which takes `io.Reader` - either `os.Stdin` or `os.File` depending on the `isInputFromPipe` method;
2. The default msgSeparator marker is **empty** (`[]byte{}`) which if you see in the implementation above leads to simply no splitting at all

With that approach we can also post-process byte-stream that is redirected with marker to a file

2022-02-03 17:28 UTC, peterklijn commented on README.md
> +Because Proto bytes can contain newlines (`\n`) and often do, we need to use a different line separator when consuming.
It's changed to a []byte in the code, I don't think this should matter for the caller

2022-02-03 17:28 UTC, peterklijn commented on cmd/json.go
> +				case e, ok := <-errorCh:
Discussed offline

2022-02-03 17:29 UTC, peterklijn commented
@rbroggi Thanks for your suggestion! It works great, the readme is clearer, and the code is cleaner as well 🚀

2022-02-03 17:48 UTC, rbroggi commented
> ```go
> MessageDescriptor()
> 	if err != nil {
> 		return err
> 	}
> 	s := bufio.NewScanner(bufio.NewReader(r))
> 	s.Split(SplitMessagesOnMarker(c.
> ```

I forgot to paste the sample code of the `cmd/json.go`:

```go
...
		r := os.Stdin
		if !isInputFromPipe() {
			r, err = getFile(args[0])
		}
		consumer := func(msg []byte) {
			_, _ = fmt.Fprintln(os.Stdout, string(msg))
		}
		err = c.Convert(r, consumer)
		if err != nil {
			return err
		}
		return nil

```

2022-02-04 06:05 UTC, rbroggi requested changes

2022-02-04 06:05 UTC, rbroggi commented on cmd/json.go
>  		if isInputFromPipe() {
There are some reasons why I think this approach is better:

1. Backwards compatibility - all the people using `proto` without a `messageMarker` will still verify the same behavior (for that our default message marker should be `[]byte{}` instead of `--END--`. 
2. We would have a consistent processing method regardless of whether we are consuming from stdin or from a file and in both cases we can process multi-msg streams.
3. Code simplified because we can get rid of the channels

2022-02-04 06:05 UTC, rbroggi commented on cmd/json.go
> +	jsonCmd.Flags().StringVarP(&endOfMessageMarker, "end-of-message-marker", "m", "",
As suggested, I think the default marker should be empty for backwards compatibility (some people might already have alias in their environments and they only consume one proto-msg at time)

2022-02-04 06:05 UTC, rbroggi commented on internal/json/json.go
> +const DefaultEndOfMessageMarker = "--END--"
I suggest to default to empty

2022-02-04 06:05 UTC, rbroggi commented on internal/json/json_test.go
> +func Test_ConvertStream(t *testing.T) {
by getting rid of the method `ConvertStream` this method would be simplified a lot (no handling channels)

2022-02-04 08:12 UTC, peterklijn commented on cmd/json.go
>  		if isInputFromPipe() {
I'm sorry, but I disagree.

1. The current implementation is backwards compatible, the current implementation reads till EOF, if your stream doesn't not contain the `--END--` marker, this will do the same. But also keep in mind that the current solution does not really work with pipes, unless you only pipe a single message. 
I don't like using empty defaults, as it would result in always providing a marker, making the tool more verbose, similar to how https://github.com/beatlabs/proton/pull/1 removes the need for a package and messageType and uses sane defaults instead, which you can override if your situation requires it.

2. Sure, unifying the the streams removes some duplication, but what you're suggesting would stop processing after one failed parsed message. That's not what I think it should do, my implementation continues if it can't parse a message, and returns a message instead. The reason for this is that I rather see other messages than end up with an unprocessable stream due to one message (maybe there's a bug in an edge case of Proton, or an invalid message in the kafka stream)

3. The channels are there because the solution will return either a result, or an error, for each line. And I want errors to go to stderr, not stdout. this way you can separate them if you were to pipe the result of Proton to something else.

Just to be clear, the current solution gives you this:


```bash
{ ... result 1 ...} # stdout
{ ... result 2 ...} # stdout
some parse error # stderr
{ ... result 4 ...} # stdout
{ ... result 5 ...} # stdout
Unexpected EOF # stderr
{ ... result 7 ...} # stdout
```

I do not want Proton to stop processing if one message can't be parsed, but rather let the user know that something failed (don't fail silently)

2022-02-04 08:26 UTC, rbroggi commented on cmd/json.go
>  		if isInputFromPipe() {
Your point about the `early` return is valid. I think we can find a middle-ground that emphasises all of our concerns, e.g.:

we can get rid of the `Convert` method and only use the `ConvertStream` (keeping the channels) but maintain the same behavior for file/stdin ( default marker is empty -> no split, marker provided -> split on the marker regardless if stream comes from file or stdin). WDYT?

2022-02-04 09:05 UTC, peterklijn commented on cmd/json.go
>  		if isInputFromPipe() {
Awesome, let's do that!

2022-02-04 11:16 UTC, rbroggi approved these changes

2022-02-04 11:30 UTC, merged